apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-secrets
  namespace: database
type: Opaque
stringData:
  ACCESS_KEY: "${CNPG_MINIO_ACCESS_KEY}"
  ACCESS_SECRET_KEY: "${CNPG_MINIO_SECRET_KEY}"