apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ubutumwa-bugufi
  namespace: database
spec:
  instances: 1
  postgresql:
    version: "18"
    dataVolume:
      size: 10Gi
      storageClass: longhorn
  bootstrap:
    initdb:
      database: ubutumwa-bugufi
      owner: ${UBUTUMWA_BUGUFI_DB_USER}
      username: ${UBUTUMWA_BUGUFI_DB_USER}
      password: ${UBUTUMWA_BUGUFI_DB_PASSWORD}
