apiVersion: v1
kind: Secret
metadata:
  name: ubutumwa-bugufi-db-user-secret
  namespace: database
type: kubernetes.io/basic-auth
data:
  username: ${UBUTUMWA_BUGUFI_DB_USER}
  password: ${UBUTUMWA_BUGUFI_DB_PASSWORD}
