apiVersion: v1
kind: Secret
metadata:
  name: ubutumwa-bugufi-db-user-secret
  namespace: database
type: Opaque
stringData:
  username: ${UBUTUMWA_BUGUFI_DB_USER}
  password: ${UBUTUMWA_BUGUFI_DB_PASSWORD}
