# Dev Database for Ubutumwa Bugufi Application
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ubutumwa-bugufi-dev
spec:
  name: ubutumwa-bugufi-dev
  owner: UbutumwaBugufiUser
  cluster:
    name: ubutumwa-bugufi
  schemas:
    - name: ub
      owner: UbutumwaBugufiUser

---
# Test Database for Ubutumwa Bugufi Application
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ubutumwa-bugufi-test
spec:
  name: ubutumwa-bugufi-test
  owner: UbutumwaBugufiUser
  cluster:
    name: ubutumwa-bugufi
  schemas:
    - name: ub
      owner: UbutumwaBugufiUser

---
# Prod Database for Ubutumwa Bugufi Application
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ubutumwa-bugufi
spec:
  name: ubutumwa-bugufi
  owner: UbutumwaBugufiUser
  cluster:
    name: ubutumwa-bugufi
  schemas:
    - name: ub
      owner: UbutumwaBugufiUser