apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ubutumwa-bugufi
  namespace: database
spec:
  instances: 1
  postgresVersion: 18
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: ubutumwa-bugufi
      owner: ubutumwa-bugufi
      secret:
        name: ubutumwa-bugufi-db-user-secret

