apiVersion: postgresql.cnpg.io/v1beta1
kind: Cluster
metadata:
  name: ubutumwa-bugufi
  namespace: database
spec:
  instances: 1
  postgresVersion: 18
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: ubutumwa-bugufi
      owner: ubutumwa_user
  users:
    - name: ubutumwa_user
      passwordSecret: ubutumwa-bugufi-db-user-secret
      databases:
        - ubutumwa-bugufi
