# ========== Grafana ==========
adminUser: admin
adminPassword: "${GRAFANA_ADMIN_PASSWORD}"
persistence:
  enabled: true
  size: 5Gi
  storageClassName: ${STORAGE_CLASS_NAME}
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - "${SUB_DOMAIN}.test.k8s.iradukunda.me"
  tls:
    - secretName: ${SUB_DOMAIN}-tls-secret
      hosts:
        - "${SUB_DOMAIN}.test.k8s.iradukunda.me"
sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true
alerting:
  contactpoints.yaml:
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: Slack Alerts
        receivers:
          - uid: slack-default
            type: slack
            settings:
              url: ${SLACK_WEBHOOK_URL}
